CREATE TABLE IF NOT EXISTS contran_normative_articles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resolution text NOT NULL,
  resolution_number text NOT NULL,
  resolution_year text NOT NULL,
  article text NOT NULL DEFAULT '',
  paragraph text NOT NULL DEFAULT '',
  item text NOT NULL DEFAULT '',
  subitem text NOT NULL DEFAULT '',
  annex text NOT NULL DEFAULT '',
  title text NOT NULL DEFAULT '',
  full_text text NOT NULL DEFAULT '',
  plain_text text NOT NULL DEFAULT '',
  source_url text NOT NULL DEFAULT '',
  source_name text NOT NULL DEFAULT '',
  source_version_date text NOT NULL DEFAULT '',
  is_current integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_contran_normative_articles_ref
  ON contran_normative_articles (
    resolution_number,
    resolution_year,
    article,
    paragraph,
    item,
    subitem,
    annex
  );

CREATE TABLE IF NOT EXISTS contran_question_normative_references (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id integer NOT NULL,
  external_id text NOT NULL DEFAULT '',
  normative_article_id integer,
  resolution text NOT NULL DEFAULT '',
  resolution_number text NOT NULL DEFAULT '',
  resolution_year text NOT NULL DEFAULT '',
  article text NOT NULL DEFAULT '',
  paragraph text NOT NULL DEFAULT '',
  item text NOT NULL DEFAULT '',
  subitem text NOT NULL DEFAULT '',
  annex text NOT NULL DEFAULT '',
  raw_reference text NOT NULL DEFAULT '',
  display_order integer NOT NULL DEFAULT 0,
  needs_normative_reference_review integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_contran_question_normative_refs
  ON contran_question_normative_references (
    question_id,
    resolution_number,
    resolution_year,
    article,
    paragraph,
    item,
    subitem,
    annex
  );

CREATE INDEX IF NOT EXISTS idx_contran_question_normative_refs_question
  ON contran_question_normative_references (question_id, display_order);

CREATE TABLE IF NOT EXISTS missing_normative_articles_queue (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resolution text NOT NULL DEFAULT '',
  resolution_number text NOT NULL DEFAULT '',
  resolution_year text NOT NULL DEFAULT '',
  article text NOT NULL DEFAULT '',
  paragraph text NOT NULL DEFAULT '',
  item text NOT NULL DEFAULT '',
  subitem text NOT NULL DEFAULT '',
  annex text NOT NULL DEFAULT '',
  question_id integer NOT NULL,
  external_id text NOT NULL DEFAULT '',
  raw_reference text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDENTE',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_missing_normative_articles_queue
  ON missing_normative_articles_queue (
    resolution_number,
    resolution_year,
    article,
    paragraph,
    item,
    subitem,
    annex,
    question_id
  );
