CREATE TABLE IF NOT EXISTS theory_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pdf_path TEXT NOT NULL,
  page_number INTEGER NOT NULL,
  page_count INTEGER,
  materia TEXT,
  assunto TEXT,
  title TEXT,
  text TEXT,
  normalized_text TEXT,
  indexed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (pdf_path, page_number)
);

CREATE INDEX IF NOT EXISTS idx_theory_pages_pdf
  ON theory_pages(pdf_path, page_number);

CREATE INDEX IF NOT EXISTS idx_theory_pages_subject
  ON theory_pages(materia, assunto);
