import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Worker } from 'node:worker_threads';

const WORKER_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), 'postgres-sync-worker.mjs');

export class PostgresSyncDatabase {
  constructor(databaseUrl) {
    if (!databaseUrl) throw new Error('DATABASE_URL nao definido para DB_CLIENT=postgres.');
    this.databaseUrl = databaseUrl;
    this.closed = false;
    this.controlBuffer = new SharedArrayBuffer(4);
    this.control = new Int32Array(this.controlBuffer);
    this.tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'prf-pg-sync-'));
    this.requestPath = path.join(this.tmpDir, 'request.json');
    this.responsePath = path.join(this.tmpDir, 'response.json');
    this.worker = new Worker(WORKER_PATH, {
      workerData: {
        databaseUrl,
        control: this.controlBuffer,
        requestPath: this.requestPath,
        responsePath: this.responsePath
      }
    });
  }

  prepare(sql) {
    const pragmaTable = parsePragmaTableInfo(sql);
    if (pragmaTable) {
      return new PostgresSyncStatement(this, '', 'pragma_table_info', { tableName: pragmaTable });
    }
    return new PostgresSyncStatement(this, translateSqliteToPostgres(sql));
  }

  exec(sqlText) {
    const statements = splitSqlStatements(stripLineComments(sqlText))
      .map((statement) => translateSqliteToPostgres(statement))
      .filter(Boolean);
    return this.request('exec', { statements });
  }

  close() {
    if (this.closed) return;
    this.closed = true;
    Atomics.store(this.control, 0, 3);
    Atomics.notify(this.control, 0, 1);
    this.worker.terminate();
    fsp.rm(this.tmpDir, { recursive: true, force: true }).catch(() => {});
  }

  request(op, payload) {
    if (this.closed) throw new Error('Conexao Postgres ja foi encerrada.');
    if (Atomics.load(this.control, 0) !== 0) {
      throw new Error('PostgresSyncDatabase recebeu chamada concorrente inesperada.');
    }

    fs.writeFileSync(this.requestPath, JSON.stringify({ op, ...payload }), 'utf8');
    Atomics.store(this.control, 0, 1);
    Atomics.notify(this.control, 0, 1);

    while (Atomics.load(this.control, 0) === 1) {
      Atomics.wait(this.control, 0, 1);
    }

    const response = JSON.parse(fs.readFileSync(this.responsePath, 'utf8'));
    fs.rmSync(this.responsePath, { force: true });
    Atomics.store(this.control, 0, 0);
    Atomics.notify(this.control, 0, 1);

    if (!response.ok) {
      const error = new Error(response.error || 'Erro Postgres');
      error.stack = response.stack || error.stack;
      throw error;
    }
    return normalizeRows(response.value);
  }
}

class PostgresSyncStatement {
  constructor(db, sql, forcedOp = '', forcedPayload = {}) {
    this.db = db;
    this.sql = sql;
    this.forcedOp = forcedOp;
    this.forcedPayload = forcedPayload;
  }

  all(...params) {
    if (this.forcedOp) return this.db.request(this.forcedOp, this.forcedPayload);
    return this.db.request('all', { sql: this.sql, params });
  }

  get(...params) {
    if (this.forcedOp) {
      const rows = this.db.request(this.forcedOp, this.forcedPayload);
      return rows[0] || null;
    }
    return this.db.request('get', { sql: this.sql, params });
  }

  run(...params) {
    if (this.forcedOp) return this.db.request(this.forcedOp, this.forcedPayload);
    return this.db.request('run', { sql: this.sql, params });
  }
}

export function translateSqliteToPostgres(sqlText) {
  let sql = String(sqlText || '').trim();
  sql = translateSqliteCatalogQuery(sql);
  sql = sql.replace(/datetime\('now'\s*,\s*'([+-])(\d+)\s+minutes?'\)/gi, (_, sign, amount) => (
    sign === '-'
      ? `(CURRENT_TIMESTAMP - INTERVAL '${Number(amount)} minutes')`
      : `(CURRENT_TIMESTAMP + INTERVAL '${Number(amount)} minutes')`
  ));
  sql = sql.replace(/datetime\('now'\s*,\s*'([+-])(\d+)\s+days?'\)/gi, (_, sign, amount) => (
    sign === '-'
      ? `(CURRENT_TIMESTAMP - INTERVAL '${Number(amount)} days')`
      : `(CURRENT_TIMESTAMP + INTERVAL '${Number(amount)} days')`
  ));
  sql = sql.replace(/datetime\('now'\)/gi, 'CURRENT_TIMESTAMP');
  sql = sql.replace(/COALESCE\(((?:(?:[A-Za-z_][\w]*\.)?[A-Za-z_][\w]*))\s*,\s*''\)\s*!=\s*''/gi, '($1 IS NOT NULL AND $1::text != \'\')');
  sql = sql.replace(/COALESCE\(((?:(?:[A-Za-z_][\w]*\.)?[A-Za-z_][\w]*))\s*,\s*''\)\s*=\s*''/gi, '($1 IS NULL OR $1::text = \'\')');
  sql = sql.replace(/\bAUTOINCREMENT\b/gi, '');
  sql = sql.replace(/\bINTEGER\s+PRIMARY\s+KEY\s*(,|\))/gi, 'integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY$1');
  sql = replacePlaceholders(sql);
  return sql;
}

function translateSqliteCatalogQuery(sql) {
  if (!/\bsqlite_(master|schema)\b/i.test(sql)) return sql;
  const literalName = sql.match(/name\s*=\s*'([^']+)'/i)?.[1];
  const namePredicate = literalName ? `table_name = '${literalName.replaceAll("'", "''")}'` : 'table_name = ?';
  return `SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND ${namePredicate}`;
}

function replacePlaceholders(sql) {
  let index = 0;
  let quote = '';
  let output = '';
  let previous = '';
  for (const char of sql) {
    if (quote) {
      output += char;
      if (char === quote && previous !== '\\') quote = '';
    } else if (char === '\'' || char === '"') {
      quote = char;
      output += char;
    } else if (char === '?') {
      index += 1;
      output += `$${index}`;
    } else {
      output += char;
    }
    previous = char;
  }
  return output;
}

function parsePragmaTableInfo(sql) {
  const match = String(sql || '').trim().match(/^PRAGMA\s+table_info\((.+)\)$/i);
  if (!match) return '';
  return match[1].trim().replace(/^["'`[]|["'`\]]$/g, '');
}

function splitSqlStatements(sqlText) {
  const statements = [];
  let current = '';
  let quote = '';
  let previous = '';
  for (const char of sqlText) {
    current += char;
    if (quote) {
      if (char === quote && previous !== '\\') quote = '';
    } else if (char === '\'' || char === '"') {
      quote = char;
    } else if (char === ';') {
      statements.push(current.slice(0, -1).trim());
      current = '';
    }
    previous = char;
  }
  if (current.trim()) statements.push(current.trim());
  return statements;
}

function stripLineComments(sqlText) {
  return String(sqlText || '')
    .split(/\r?\n/)
    .filter((line) => !line.trim().startsWith('--'))
    .join('\n');
}

function normalizeRows(value) {
  if (Array.isArray(value)) {
    return value.map(normalizeRow);
  }
  return normalizeRow(value);
}

function normalizeRow(row) {
    if (!row || typeof row !== 'object') return row;
    const normalized = {};
    for (const [key, item] of Object.entries(row)) {
      normalized[key] = normalizeValue(key, item);
    }
    return normalized;
}

function normalizeValue(key, value) {
  if (typeof value !== 'string') return value;
  if (!/^-?\d+(\.\d+)?$/.test(value)) return value;
  if (/(^|_)(text|html|json|url|source|answer|letter|key|label|name|status|mode|type|notes?)$/i.test(key)) {
    return value;
  }
  const numeric = Number(value);
  return Number.isSafeInteger(numeric) || value.includes('.') ? numeric : value;
}
